### ISSUE TITLE
double disconnect on for ON_FORCE_SYNC 

### ISSUE THREAD

**Issue by nik-markovic** [avnet-iotconnect/iotc-generic-c-sdk#14]
A copy and paste error. The extra disconnect should be removed.

**Comment by nmatthews-witekio** [comment]
Wondering whether there should also be some sort of (re-)connect, e.g. iotcl_init().

Maybe iotconnect_sdk_disconnect() should free sync_response and discovery_response, so they are destroyed whenever SDK is disconnected?

**Comment by nik-markovic** [comment]
I think that the idea is that MQTT should be robust enough to maintain the connection. A full clean reconnect at user level along even with http dicovery/sync would maybe be preferred to over some risky partial reconnect that could have bugs. It's not like we are giving the code to the customers wrapped in a sealed container. They can ask us to make changes and they can make the changes on their end easily. I am not saying that adding it would not help, but I felt that for example NRF SDK's changes from Singapore team just added to the complexity, even though the changes were of very high quality and added some useful features (like re-transmit).

Also, keep in mind immediate reconnect in the same callback where we receive the FORCE SYNC or disconnect is probably incorrect at the SDK level. It is likely that that callback will come from a stack that's smaller, or could cause a race condition. It is best that the application handles the reconnect scenario.

Technically, unless FORCE_SYNC means that we must drop cache, we could continue to cache what we received from a successful sync and discovery. A disconnect (user or network side) "should" not trigger a new sync because the new sync will simply add extra time to reconnection and will return the same data as the previous one in 99.999999% of the cases. The rest of the scenarios would be some edge cases or cases where some large change would be made. In any case, in most SDKs I think that we do NOT cache sync just because I felt that it was cleaner maybe. This one, we probably do.

**Comment by nmatthews-witekio** [comment]
Ok, I may be misunderstanding FORCE_SYNC -- not sure where it's documented.

I was wondering how to get device to redo discovery/sync in case server is changed.
I saw FORCE_SYNC in C-SDK and assumed that was a mechanism to facilitate that.
