### ISSUE TITLE
OpenSSL deprecation warnings with -DIOTC_USE_PAHO=ON

### ISSUE THREAD

**Issue by nmatthews-witekio** [avnet-iotconnect/iotc-generic-c-sdk#21]
> /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c: In function ‘WebSocket_upgrade’:
> /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:1329:17: warning: ‘SHA1_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
>  1329 |                 SHA1_Init( &ctx );
>       |                 ^~~~~~~~~
> In file included from /usr/include/openssl/x509.h:41,
>                  from /usr/include/openssl/ssl.h:31,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/SSLSocket.h:29,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/MQTTPacket.h:26,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.h:20,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:30:
> /usr/include/openssl/sha.h:49:27: note: declared here
>    49 | OSSL_DEPRECATEDIN_3_0 int SHA1_Init(SHA_CTX *c);
>       |                           ^~~~~~~~~
> /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:1330:17: warning: ‘SHA1_Update’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
>  1330 |                 SHA1_Update( &ctx, ws_key, strlen(ws_key));
>       |                 ^~~~~~~~~~~
> In file included from /usr/include/openssl/x509.h:41,
>                  from /usr/include/openssl/ssl.h:31,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/SSLSocket.h:29,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/MQTTPacket.h:26,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.h:20,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:30:
> /usr/include/openssl/sha.h:50:27: note: declared here
>    50 | OSSL_DEPRECATEDIN_3_0 int SHA1_Update(SHA_CTX *c, const void *data, size_t len);
>       |                           ^~~~~~~~~~~
> /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:1331:17: warning: ‘SHA1_Final’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
>  1331 |                 SHA1_Final( sha_hash, &ctx );
>       |                 ^~~~~~~~~~
> In file included from /usr/include/openssl/x509.h:41,
>                  from /usr/include/openssl/ssl.h:31,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/SSLSocket.h:29,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/MQTTPacket.h:26,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.h:20,
>                  from /witekio/work/iotconnect/github/public/iotc-generic-c-sdk/lib/paho.mqtt.c/src/WebSocket.c:30:
> /usr/include/openssl/sha.h:51:27: note: declared here
>    51 | OSSL_DEPRECATEDIN_3_0 int SHA1_Final(unsigned char *md, SHA_CTX *c);
>       |                           ^~~~~~~~~~
>

**Comment by nmatthews-witekio** [comment]
Unfortunately, upgrading in https://github.com/avnet-iotconnect/iotc-generic-c-sdk/pull/33 doesn't solve this.

**Comment by nik-markovic** [comment]
Closing as the Protocol 1.0 branch is in maintenance mode now, so we will only address critical bugs and features.
